export const EMPLOYEE_LIST = "EMPLOYEE_LIST";
export const SET_EMPLOYEE_LIST = "SET_EMPLOYEE_LIST";

export const CREATE_USER_START = "CREATE_USER_START";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_ERROR = "CREATE_USER_ERROR";
